
FROM hseeberger/scala-sbt:8u302_1.5.5_2.13.6

RUN mkdir -p /common

COPY ./scala-common /common

RUN cd /common && sbt +publishLocal && cd ..

RUN mkdir -p /spark

WORKDIR /spark

COPY ./spark /spark
